apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: cpu-nodegroup-labels
spec:
  rules:
    - name: "CPU nodes"
      labels:
        workload-type: "cpu"
      matchFeatures:
        - feature: system.name
          matchExpressions:
            nodename:
              op: InRegexp
              value:
                - "cpu"
