apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: gpu-node-taint
spec:
  rules:
    - name: "Taint GPU nodes"
      taints:
        - effect: NoSchedule
          key: "nvidia.com/gpu"
          value: "true"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: {op: In, value: ["10de"]}
